### ISSUE TITLE
Errors on Linux

### ISSUE THREAD

**Issue by larsb24** [TerminalStudio/flutter_pty#1]
First, there seems to be a typo in CMakeLists.txt which calls for "flutter_pty.cc" but the file is called "flutter_pty.c"

After fixing that, building on Linux fails with a missing library:

```
> flutter run -d linux
Launching lib/main.dart on Linux in debug mode...
/home/user/Development/flutter_pty/example/linux/flutter/ephemeral/.plugin_symlinks/flutter_pty/src/flutter_pty.h:11:10: fatal error: 'util.h' file not found
Building Linux application...                                           
Exception: Build process failed
```

**Comment by xtyxtyx** [comment]
Hello, thanks for reporting this issue!
This has been fixed and published to pub.dev. You can try upgrading to 0.0.7 to see if it works.

**Comment by larsb24** [comment]
Yup, seems to be fixed. Thanks a lot!
