### ISSUE TITLE
Permission denied on android 11

### ISSUE THREAD

**Issue by azkadev** [TerminalStudio/flutter_pty#8]
I tried your library and used in app to run exe binary but always permission denied, I did chmod 777 but it doesn't work how to do it?

**Comment by Cateners** [comment]
@azkadev I encountered the same issue as you did. May I know how you resolved it?

**Comment by Cateners** [comment]
Oh, I got it. I have to set the targetSdkVersion lower than Android Q.
https://github.com/termux/termux-app/issues/1072
Although I saw this article a long time ago, I will never pay attention to it unless there is an issue with my project.
